[tool.poetry]
name = "epyq"
version = "2021.5.1.post100.dev0+8677039"
description = ""
authors = ["alex anker <alex.anker@epcpower.com>"]
license = "GPL-2.0-or-later"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files = ["src/epyq/__init__.py"]

[tool.poetry.dependencies]
python = "3.7.9"
alqtendpy = "0.0.4"
pyinstaller = "~=4.5"
graham = "0.1.11"
python-can = "4.0.0.dev0"
bitstruct = "6.0.0"
Twisted = "21.2.0"
qt5reactor = "0.5"
pyelftools = "0.26"
attrs = ">=19.3.0"
natsort = "5.5.0"
arrow = "0.12.1"
PyQtChart = "5.14.0"
pytest = "5.3.5"
pytest-faulthandler = "1.5.0"
pytest-rerunfailures = "5.0"
pytest-qt = "3.3.0"
pywin32 = { version = "223", markers = "sys_platform == 'win32'" }
certitude = { version = "1.0.1", markers = "sys_platform == 'Darwin'" }
#pytest-twisted = {git = "https://github.com/altendky/pytest-twisted", rev = "6f04ba3ad806b3b40602999e71c28633c36d81f9"}
pytest-twisted = "<=1.13.4"
pysunspec = "2.1.0"
sunspecdemo = {git = "https://github.com/epcpower/sunspec-demo", rev = "6a07576a9d3c16f00a31121ff96edcbfe0d73822"}
pluggy = "0.12.0"
appdirs = "1.4.3"
boto3 = "1.14.41.0"
boto3-type-annotations = "0.3.1"
certifi = "2020.6.20"
paho-mqtt = "1.4.0"
treq = "21.1.0"
siphash-cffi = "^0.1.4"
epyqlib = {path = "./sub/epyqlib",  develop = true}
PyQt5 = "5.14.1"
pyqtdeploy = "^3.1.1"

[tool.poetry.dev-dependencies]
poetry-dynamic-versioning = "^0.13.1"
black = "20.8b1"

[tool.poetry.scripts]
buildui = 'buildui:compile_ui'
epyq = 'epyq.__main__:main'


[tool.black]
target-version =  ['py37']
include = '''
(
    /download_fonts.py
    | /pinsys.py
    | /src/epyq/.*\.pyi?
    | /buildui.py
)$
'''
exclude = ''

[build-system]
requires = [
    "alqtendpy",
    "setuptools",
    "wheel",
    "poetry-core>=1.0.0",
    "poetry-dynamic-versioning",
]
build-backend = "poetry.core.masonry.api"
