[tool.poetry]
name = "epyq"
version = "0.1.0"
description = ""
authors = ["alex anker <alex.anker@epcpower.com>"]

[tool.poetry.dependencies]
python = "^3.7"
alqtendpy = "0.0.4"
pyinstaller = "~=4.5"
graham = "0.1.11"
python-can = {git = "https://github.com/hardbyte/python-can", rev = "2ede107d67002c18463c5276b6a94cdb19fc8320"}
bitstruct = {git = "https://github.com/altendky/bitstruct", rev = "c1ff0e635257e7be0cf2e4dbdf8a12b8faf83e7f"}
Twisted = "21.2.0"
qt5reactor = {git = "https://github.com/altendky/qt5reactor", rev = "ce3ea2dad6d71adb10cde79b64bc0c7d27e9139c"}
pyelftools = {git = "https://github.com/eliben/pyelftools", rev = "27941c50fef8cff8ef991419511664154c8cdf52"}
attrs = "19.3.0"
natsort = "5.4.1"
arrow = "0.12.1"
black = "20.8b1"
PyQtChart = "5.14.0"
pytest = "3.9.2"
pytest-faulthandler = "1.5.0"
pytest-rerunfailures = "4.2"
pytest-qt = "3.2.1"
pywin32 = { version = "223", markers = "sys_platform == 'win32'" }
certitude = { version = "1.0.1", markers = "sys_platform == 'Darwin'" }
#pytest-twisted = {git = "https://github.com/altendky/pytest-twisted", rev = "6f04ba3ad806b3b40602999e71c28633c36d81f9"}
pytest-twisted = "1.12"

pysunspec = {git = "https://github.com/altendky/pysunspec", rev = "d8072a8e3c04693fe2a657a90fc9d303037dd91c"}
epcsunspecdemo = {git = "https://github.com/epcpower/sunspec-demo", rev = "19581317ae2fd136b5df229d824f81a17da52c58"}
pluggy = "0.11.0"
appdirs = "1.4.3"
boto3 = "1.9.83"
boto3-type-annotations = "0.3.0"
certifi = "2019.3.9"
paho-mqtt = "1.4.0"
treq = "21.1.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
buildui = 'buildui:compile_ui'

[tool.black]
target-version =  ['py37']
include = '''
(
    /setup.py
    | /deploy_win.py
    | /download_fonts.py
    | /pinsys.py
    | /src/epyq/.*\.pyi?
)$
'''
exclude = ''

[build-system]
requires = [
    "alqtendpy",
    "setuptools",
    "wheel",
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

