[tool.poetry]
name = "epyq"
version = "0.1.0"
description = ""
authors = ["alex anker <alex.anker@epcpower.com>"]

[tool.poetry.dependencies]
python = "^3.7"
alqtendpy = "0.0.4"
pyinstaller = "~=4.5"
graham = "0.1.11"
python-can = {git = "https://github.com/hardbyte/python-can", rev = "2ede107d67002c18463c5276b6a94cdb19fc8320"}
bitstruct = "6.0.0"
Twisted = "21.2.0"
qt5reactor = "0.5"
pyelftools = "0.25"
attrs = "19.3.0"
natsort = "5.5.0"
arrow = "0.12.1"
black = "20.8b1"
PyQtChart = "5.14.0"
pytest = "5.3.5"
pytest-faulthandler = "1.5.0"
pytest-rerunfailures = "5.0"
pytest-qt = "3.3.0"
pywin32 = { version = "223", markers = "sys_platform == 'win32'" }
certitude = { version = "1.0.1", markers = "sys_platform == 'Darwin'" }
#pytest-twisted = {git = "https://github.com/altendky/pytest-twisted", rev = "6f04ba3ad806b3b40602999e71c28633c36d81f9"}
pytest-twisted = "1.12"

pysunspec = {git = "https://github.com/altendky/pysunspec", rev = "ad7ca25964ca8071c652fb5836af6e7286dc48dc"}
epcsunspecdemo = {git = "https://github.com/epcpower/sunspec-demo", rev = "19581317ae2fd136b5df229d824f81a17da52c58"}
pluggy = "0.12.0"
appdirs = "1.4.3"
boto3 = "1.14.41.0"
boto3-type-annotations = "0.3.1"
certifi = "2020.6.20"
paho-mqtt = "1.4.0"
treq = "21.1.0"
siphash-cffi = "^0.1.4"
epyqlib = {path = "sub/epyqlib"}
PyQt5 = "5.14.1"
pyqtdeploy = "^3.1.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
buildui = 'buildui:compile_ui'

[tool.black]
target-version =  ['py37']
include = '''
(
    /setup.py
    | /deploy_win.py
    | /deploy_win2.py
    | /download_fonts.py
    | /pinsys.py
    | /src/epyq/.*\.pyi?
)$
'''
exclude = ''

[build-system]
requires = [
    "alqtendpy",
    "setuptools",
    "wheel",
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

