#!/bin/bash

export NAME="st.hmi"
export DEST_PATH="/opt/${NAME}"
export SSH_CMD='ssh -oKexAlgorithms=+diffie-hellman-group1-sha1'
export SSH_HOST='root@169.254.1.42'
rsync -avz --delete --exclude '.git' --exclude 'venv' --rsync-path=/opt/epc/bin/rsync -e "${SSH_CMD}" . ${SSH_HOST}:"${DEST_PATH}"
${SSH_CMD} ${SSH_HOST}  mkdir -p "${DEST_PATH}"/venv/src
rsync -avz --delete --rsync-path=/opt/epc/bin/rsync -e "${SSH_CMD}" venv/src/ ${SSH_HOST}:"${DEST_PATH}/venv/src"

if [ "$1" != "--no-install" ]; then
    ${SSH_CMD} ${SSH_HOST} "\"${DEST_PATH}/reinstall-st.hmi\" --no-tar"
fi
