name: CI

on:
  push:
    branches:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
    tags:
      - "**" #double star includes a '/'.  single star doesnt match a '/'
  schedule:
    # Daily at 05:44
    - cron: '44 5 * * *'

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.7
  AWS_REGION: us-east-2
  #Supports deploy_win finding python license for the epyq installer
  PYTHON: c:/hostedtoolcache/windows/Python/3.7.9/x64


jobs:
  build:
    name: CI
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}          
      - name: Setup Venv
        run: |
          #install Poetry
          python3 -m ensurepip
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry==1.5.1

          poetry --version 

          poetry config virtualenvs.in-project true
          poetry config virtualenvs.path .

          #Setup AWS Connection
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain epc-power-us --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
          poetry config repositories.epc-power https://epc-power-us-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.us-east-2.amazonaws.com/pypi/epc-power/
          poetry config http-basic.epc-power aws $CODEARTIFACT_AUTH_TOKEN
          poetry config repositories.third-party https://epc-power-us-${{ secrets.AWS_ACCOUNT_ID }}.d.codeartifact.us-east-2.amazonaws.com/pypi/third-party/
          poetry config http-basic.third-party aws $CODEARTIFACT_AUTH_TOKEN
          # https://github.com/python-poetry/poetry/issues/7611
          poetry config installer.max-workers 1

          poetry install
      - name: python commands
        env:
          PHRASE: ${{ secrets.AUTOPARAMETERS_PASSPHRASE }}
        run: |
          set -vx
          poetry run buildui
          cat src/epyq/__init__.py
          echo "RUNNING POETRY DYNAMIC VERSIoNING"
          poetry self add "poetry-dynamic-versioning[plugin]"
          echo "AFTER: INIT="
          cat src/epyq/__init__.py
          poetry run black --check --diff .
          poetry run python download_fonts.py src/libs
          poetry run genbuildinfo "src/epyq/_build.py"
          poetry run pip freeze --all

          if [ -n "$PHRASE" ]; then echo -n "$PHRASE" > sub/epyqlib/epyqlib/resources/code; fi

          readlink --canonicalize-missing qtifw

          curl --location --output qtifw.exe "https://download.qt.io/official_releases/qt-installer-framework/4.1.1/QtInstallerFramework-windows-x86-4.1.1.exe"
          ./qtifw.exe in --al -c --root $(readlink --canonicalize-missing qtifw)

          poetry run python pinsis.py --qtifw
          mkdir artifacts

          mv ../*.exe artifacts/

          poetry run autodevice create template --zip="artifacts/autodevice_template-$(.venv/Scripts/python -c 'import epyq; print(f"{epyq.__version_tag__}-{epyq.__build_tag__}", end="")').zip"

          # TODO: Add this back.  Removed since it is not mandatory and was
          #       hanging the build in GitHub Actions.  Maybe due to Windows
          #       popping up a dialog asking for authorization to install it?
          # curl --location --output PeakOemDrv.exe "https://www.peak-system.com/produktcd/Drivers/PeakOemDrv.exe"
          # ls
          # ./PeakOemDrv.exe /exenoui /qn ADDLOCAL=F_PNP_DVRS,F_PCANBASIC
          poetry run python -m pytest -vvvv -s --no-qt-log --run-factory sub/epyqlib/epyqlib/tests

      - name: Publish executable
        #only run if a new tag is created
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          poetry build
          poetry publish --repository epc-power
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: epyq_st
          path: |
            artifacts/*
